import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useRef } from 'react'
import paginationImg from "../../public/images/articles/pagination component in reactjs.jpg"
import articleImage1 from "../../public/images/articles/create loading screen in react js.jpg"
import { motion, useMotionValue } from 'framer-motion'
import TransitionEffect from '@/components/TransitionEffect'

const FramerImage = motion(Image)

const MovingImg = ({title, img, link}) => {

    const x = useMotionValue(0)
    const y = useMotionValue(0)
    const imageRef = useRef(null)

    function handleMouse(event) {
        imageRef.current.style.display = "inline-block"
        x.set((event.pageX)-250)
        y.set(-10)
    }

    function handleMouseLeave() {
        imageRef.current.style.display = "none"
        x.set(0)
        y.set(0)
    }

    return (
        
        <Link href={link} target='_blank'
        onMouseMove={handleMouse}
        onMouseLeave={handleMouseLeave}
        >
            
            <span className='font-bold text-xl hover:underline underline-offset-2'>{title}</span>
            <FramerImage
            style={{x:x, y:y}}
            initial={{opacity:0}}
            whileInView={{opacity:1, transition:{duration:0.3} }}
            ref={imageRef} src={img} alt={title} className='w-96 h-auto hidden absolute rounded-lg z-10' />
        </Link>
        
    )
    
}




const FeaturedArticle = ({title, summary, readTime, img, link}) => {
    return (
        <li className='relative col-span-1 w-full rounded-2xl border border-solid border-dark bg-light p-4 '>

            <div className='absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2rem] bg-dark rounded-br-3xl'/>

            <Link href={link} target='_blank' className='w-full cursor-pointer inline-block overflow-hidden rounded-lg '>

                <Image src={img} alt={title} className='w-full h-auto rounded-lg hover:scale-105 ease-in duration-300 mb-1'
                priority={true}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                />

            </Link>

            <div className='w-full flex flex-col items-start justify-between'>
                
                <Link href={link}  target="_blank" className='hover:underline underline-offset-2 overflow-hidden'>
                    <h2 className='w-full my-2 text-left text-2xl font-bold capitalize'>{title}</h2>
                </Link>
                <p className='my-2 text-sm text-dark'>{summary}</p>
                <span className='text-primary font-semibold text-xl'>{readTime} min read</span>
            </div>
        </li>
    )
}

const Article = ({title, date, link, img}) => {
    return (
        <motion.li
            initial={{y:100}}
            whileInView={{y:0, transition:{duration:0.3, ease:"easeInOut"}}}
            viewport={{once:true}}
            className="relative w-full bg-light border border-solid border-dark border-r-4 border-b-4 py-8 px-4 rounded-xl  flex items-center justify-between my-4 text-dark">
            <MovingImg
            title={title}
            img={img}
            link={link}
            />
            <span className='text-primary font-semibold'>{date}</span>
        </motion.li>
    )
}

const articles = () => {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <TransitionEffect/>
    <main className='w-full mb-16 flex flex-col items-center justify-center overflow-hidden'>
        <Layout className='pt-16'>
        <AnimatedText text={"Captain's Log"} classname='mb-16'/>

        <ul className='grid grid-cols-2 gap-16'>
            
            <FeaturedArticle
                title={"Build A Custom Pagination Component In Reactjs From Scratch"}
                summary={"Learn how to build a custom pagination component in ReactJS from scratch. Follow this step-by-step guide to integrate Pagination component in your ReactJS project."}
                readTime={9}
                link={"/"}
                img={paginationImg}
            />
        
        
            <FeaturedArticle
                title={"Build A Custom Pagination Component In Reactjs From Scratch"}
                summary={"Learn how to build a custom pagination component in ReactJS from scratch. Follow this step-by-step guide to integrate Pagination component in your ReactJS project."}
                readTime={9}
                link={"/"}
                img={paginationImg}
            />
            
            

        </ul>        

        <h2 className="font-bold text-xl w-full text-center mb-8 mt-32">All Articles</h2>    
        <ul className="w-full">
        <Article
                title={"This is a test"}
                date={"July 25th, 2023"}
                link={"/"}
                img={articleImage1}
            />

            <Article
                title={"This is a test"}
                date={"July 25th, 2023"}
                link={"/"}
                img={articleImage1}
            />

            <Article
                title={"This is a test"}
                date={"July 25th, 2023"}
                link={"/"}
                img={articleImage1}
            />

            <Article
                title={"This is a test"}
                date={"July 25th, 2023"}
                link={"/"}
                img={articleImage1}
            />

            <Article
                title={"This is a test"}
                date={"July 25th, 2023"}
                link={"/"}
                img={articleImage1}
            />

            <Article
                title={"This is a test"}
                date={"July 25th, 2023"}
                link={"/"}
                img={articleImage1}
            />
        </ul>
        </Layout>
    </main>
    
    </>


   
  )
}

export default articles